Enumerable methods
hillarioh/ruby-enumerable pull request #1
Opened 2020-04-25 05:45 UTC by hillarioh

This is a solo project in the basic ruby course that entails creating methods that perform the same function as enumerable methods.

2020-04-25 08:10 UTC, mosesogwo requested changes
**Hi @hillarioh, good work:+1: but we need to fix the following:**
- For **my_each, my_each_with_index , my_select and my_map** methods, they should return an enumerator with members of the given enum when no block is given instead of returning `nil`

- For **my_all?, my_any? and my_none?** methods, make sure you handle the scenarios when a Class, or a Regex or any other pattern is given as argument. See this [documentation](https://ruby-doc.org/core-2.6.5/Enumerable.html) for the expected behaviours. The methods should be able to receive an optional argument so that you can have operations like `['a', 'b', 'c'].my_all?(String)`, to return `true`

- **my_all?** should return true when no block is given and none of the members is false or nil.

- **my_any?** should return true when no block is given and there is at least one member that is not false or nil.

- **my_none?** should return true when no block is given and none of the members of the given enum is true.

- **my_inject** should be able to take a symbol as argument and combine the elements of the given enum using the named binary operation of that symbol. Example `[1, 2, 3, 5].my_inject(:+)` should return `11`. IT should also be able to take a starting value and symbol as second argument.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-25 08:10 UTC, mosesogwo commented on README.md
> +It is a project about building methods with same functionality as the enurable methods
You could include a list of the methods created.

2020-04-26 01:48 UTC, Forison requested changes
## Status:: Require changes❌ 
# Hi @hillarioh,
You have done a good job so far, the issues raised in the previous review have not been addressed🤔. Here are a few changes you have to make to get this project approved.
> note: your methods are supposed to mimic the behavior(functionalities) of ruby's preexisting enumerable methods.
* [ ] ```my_each```, ```my_each_with_index```, ```my_select``` and ```my_map``` ought to return an enumerator when no block is given.
* [ ] As mentioned earlier ```p ['a', 'b', 'c'].my_all?(String)``` should return ```true```
* [ ] As mentioned earlier, my_all? should return true when no block is given and none of the members is false
* [ ] As mentioned earlier, my_any? should return true when no block is given and there is at least one member that is not false or nil.
* [ ] As mentioned earlier, my_none? should return true when no block is given and none of the members of the given enum is true.
* [ ] As mentioned earlier, my_inject should be able to take a symbol as argument and combine the elements of the given enum using the named binary operation of that symbol. Example [1, 2, 3, 5].my_inject(:+) should return 11. IT should also be able to take a starting value and symbol as second argument.
## check my comments below👇
## That is it, kindly make these changes and submit the project for review😊.
#### Happy coding 😎
Addo

2020-04-26 01:48 UTC, Forison commented on script.rb
> +    return puts "#{self} has no blockk" unless block_given?
#### return enum(:name_of method) unless block_given?

2020-04-26 01:48 UTC, Forison commented on script.rb
> +    return puts "#{self} has no blockk" unless block_given?
#### return enum(:name_of method) unless block_given?

2020-04-26 01:48 UTC, Forison commented on script.rb
> +    return puts "#{self} has no block" unless block_given?
return enum(:name_of method) unless block_given?

2020-04-26 15:41 UTC, pelzolga123 requested changes
The project requires changes.

2020-04-26 15:41 UTC, pelzolga123 commented
## Hi Lecrae! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### You did a good job so far!
But still, not all methods work correctly:
*  #### My_all?
* [ ] When a pattern other than Regex or a Class is given should return true if all of the collection matches the pattern. For example:
`[3,3,3].my_all?(3)` - should return true

*  #### My_any?
* [ ] When no block or argument is given should return true if at least one of the collection is not false or nil. For example:
`[nil, false, true, []].my_any?` - should return true

* [ ] When a pattern other than Regex or a Class is given should return false if none of the collection matches the pattern. For example:
`['dog', 'bird', 'fish'].my_any?('cat')` - should return false

*  #### My_none?
* [ ] When no block or argument is given should return true only if none of the collection members is true. For example:
`[nil, false, true, []].my_none?` - should return false

* [ ] When a pattern other than Regex or a Class is given should return true only if none of the collection matches the pattern. For example:
`['dog', 'bird', 'fish'].my_none?(5)` - should return true

*  #### My_inject
* [ ] Should combine all elements of enum by applying a binary operation, specified by a block. To test your code you can use an example below, `my_inject` method should return the same value as `inject`.
```ruby
array = Array.new(10) { rand(0...10) }
operation = proc { |sum, n| sum + n }

p array.my_inject(&operation) 
p array.inject(&operation)
```
 
* [ ] When a symbol is specified should combine each element of the collection by applying the symbol as a named method. To test your code you can use an example below, `my_inject` method should return the same value as `inject`.
```ruby
array = Array.new(10) { rand(0...10) }

p array.my_inject(:+) 
p array.inject(:+)
```
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-04-27 18:24 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @hillarioh :wave: 
Good job :clap: , you are almost done. Let's cover the addressed issues to declare it as complete.
___
### :spades:  Mandatory Changes :spades: 
___
1. I can see that you have altered the rubocop config file. You should not do that. Please make sure that you are using [this](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml) config.
2. Please fix the methods below by following the comments attached sections.
- my_all?
- my_none?
- my_any?
- my_inject
____
##### Please fix the mentioned issues and send another review request.
____
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-27 18:24 UTC, shshamim63 commented on script.rb
> +    elsif !val.nil? && !(val.instance_of? Integer) && !(val.instance_of? String)
not only Integer or String `val` can be an instance of Array to. So covering them using a specific class, gonna be really long. think about using a .class. You can check `puts 3.class` on a ruby compiler. And can modify that to reach your goal.

2020-04-27 18:24 UTC, shshamim63 commented on script.rb
> +  end
`my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)) 
- when a class is passed as an argument returns true if all of the collection is a member of such class
```ruby
[1, 2, 3].my_all?(Integer) #should return true
[1, 2, nil].my_all?(Integer) #should return false
[[1, 2, 3],[1, 2]].my_all?(Array)  #should return true
```
**There are a lot of options to refactor the code. Try to find out the core conditions. After that figure out the sub supporting condition. The core condition I can see is if a block is given or not.**

2020-04-27 18:24 UTC, shshamim63 commented on script.rb
> +  end
`my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- when no block or argument is given returns true if at least one of the collection is not false or nil
```ruby
[1, 2, 3].my_any? #should return true
[1, 2, nil].my_any? #should return true
[false, false, nil].my_any? #should return false
```
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
```ruby
[1, 2, 3].my_any?(Integer) #should return true
[1, 'demo', false].my_any?(Integer) #should return true
['demo', false, nil].my_any?(Integer) #should return false
```

2020-04-27 18:24 UTC, shshamim63 commented on script.rb
> +  end
`my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- when a class is passed as an argument returns true if none of the collection is a member of such class
```ruby
[1, 2, 3].my_none?(String)  #should return true
['1', '2', '3'].my_none?(String)  #should return false
```

2020-04-27 18:24 UTC, shshamim63 commented on script.rb
> +  end
`my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- combines all elements of enum by applying a binary operation, specified by a block
```ruby
[1, 2, 3].my_inject { |memo, num| memo + num } #should return 6
[1, 2, 3].my_inject(1) { |memo, num| memo + num } #should return 7
```
- when a symbol is specified combines each element of the collection by applying the symbol as a named method
```ruby
[1, 2, 3].my_inject(:+)  #should return 6
[1, 2, 3].my_inject(1, :+)  #should return 7
```
- inject can perform on range too.
___
Well, you can say that you are having the exact result. But your approach is updating the existing array, it should not. Take a look at the following code. And try to execute it in your main.rb
```ruby
ARRAY_SIZE = 10
LOWEST_VALUE = 1
HIGHEST_VALUE = 20
array = Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) }
operation = proc { |sum, n| sum + n }

p array.inject(&operation)
p array.my_inject(&operation)

print array
p array.my_inject(:+)
print array
p array.inject(:+)

p array.my_inject(3, :*) == array.inject(3, :*)
p array.inject(3, :*) == array.my_inject(3, :*)
```

2020-04-28 12:08 UTC, stratospherique requested changes
### Impressive work @hillarioh :clap: :clap: However, few methods need further refactoring in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your methods :gear: 

### That's it :relaxed: When finished, kindly submit another code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-04-28 12:08 UTC, stratospherique commented on script.rb
> +  end
* [ ] should have working `my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
  ```ruby
    array = [1,2,5,4,7]
    p array.my_any?(Integer) == array.any?(Integer) # false
  ```

2020-04-28 12:08 UTC, stratospherique commented on script.rb
> +  end
* [ ] should have working `my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
  ```ruby
    array = [nil, false, nil, false]
    p array.my_none? == array.none? # false
  ```

2020-04-28 12:08 UTC, stratospherique commented on script.rb
> +p %w[1 2 3].my_none?(String) # should return false
- **[REQUIRED]** All commented or debugging related code should not be committed. :pray:  delete it.

2020-04-28 14:37 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: However, one method needs a bit of refactoring in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your methods

### That's it :relieved: When finished, kindly submit another code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-04-28 14:37 UTC, stratospherique commented on script.rb
> +  end
* [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
  ```ruby
    array = [1,2,5,4,7]
    p array.my_none? == array.none? # false
  ```

2020-04-28 18:57 UTC, mosesogwo approved these changes
**Congratulations:trophy: I applaud your doggedness:+1:**

You can now merge this branch.

**Cheers:stars:**

### Status: Approved:heavy_check_mark:

2020-04-28 18:57 UTC, mosesogwo commented on README.md
> +Repl.it(https://repl.it/@okerioh/enumarable-methods )
You can make this a hyperlink by writing this: `[Repl.it](https://repl.it/@okerioh/enumarable-methods)`

2020-04-28 19:11 UTC, merged